plugins: [jekyll-paginate, jekyll-minifier]

color: "#0066FF"
permalink: /blog/:categories/:title
paginate: 5

jekyll-minifier:
  remove_spaces_inside_tags: true
  remove_multi_spaces: true
  remove_intertag_spaces: true
