plugins: [jekyll-paginate, jekyll-minifier]

color: "#0066FF"
permalink: /blog/:categories/:title/
paginate: 1
paginate_path: "test.html/page:num"

jekyll-minifier:
  remove_spaces_inside_tags: true
  remove_multi_spaces: true
  remove_intertag_spaces: true
