plugins: [jekyll-paginate, jekyll-minifier]

permalink: /posts/:categories/:title/
paginate: 10
paginate_path: "posts/page:num"
highlighter: rouge

jekyll-minifier:
  remove_spaces_inside_tags: true
  remove_multi_spaces: true
  remove_intertag_spaces: true
